# Turn signal command enumeration
TurnSignal cmd

DoorRequest door_request_right_rear

uint8 rolling_counter

HighBeam high_beam_cmd

WiperFront front_wiper_cmd

WiperRear rear_wiper_cmd

Ignition ignition_cmd
DoorRequest door_request_left_rear
DoorRequest door_request_lift_gate

bool block_standard_cruise_buttons
bool block_adaptive_cruise_buttons
bool block_turn_signal_stalk

bool horn_cmd

LowBeam low_beam_cmd
